PERCENT_MULTIPLIER = 100
ROUND_DECIMALS = 2

SKILL_WEIGHT = 60
SECTION_WEIGHT = 20
CONTACT_WEIGHT = 10
COMPLETENESS_WEIGHT = 10

RESUME_SECTION_WEIGHT = 50
RESUME_CONTACT_WEIGHT = 20
RESUME_COMPLETENESS_WEIGHT = 30

EXCELLENT_SCORE_THRESHOLD = 90
VERY_GOOD_SCORE_THRESHOLD = 75
GOOD_SCORE_THRESHOLD = 60
AVERAGE_SCORE_THRESHOLD = 40

SKILLS_FILE_NAME = "skills.json"
